services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      # MySQL의 실제 데이터 파일은 여기에 저장됨
      - hsu_auto_scheduler_mysql_data:/var/lib/mysql

      # 컨테이너 최초 실행 시 init.sql 자동 실행
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

      # SQL 파일 접근용
      - ./sql:/sql
  nestjs:
    build:
      context: ./hsu-auto-scheduler-be
      dockerfile: dockerfile.prod
    ports:
      - ${NESTJS_PORT}:5000
    environment:
      PORT: ${NESTJS_PORT}
      ENV: ${ENV}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      FAST_API_BASE_URL: ${FAST_API_BASE_URL}
  fastapi:
    build:
      context: ./ortools-scheduler
      dockerfile: dockerfile.prod
    ports:
      - ${FASTAPI_PORT}:80

volumes:
  hsu_auto_scheduler_mysql_data:
