services:
  mysql:
    image: mysql:8.4
    container_name: hsu_auto_scheduler_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1316
      MYSQL_DATABASE: hsu_auto_scheduler
      MYSQL_USER: dba1
      MYSQL_PASSWORD: qscz2973@
    ports:
      - "3307:3306"
    volumes:
      # MySQL의 실제 데이터 파일은 여기에 저장됨
      - hsu_auto_scheduler_mysql_data:/var/lib/mysql

      # 컨테이너 최초 실행 시 init.sql 자동 실행
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

      # SQL 파일 접근용
      - ./sql:/sql

volumes:
  hsu_auto_scheduler_mysql_data:
